wppconnect-team/wppconnect-server

src/config.json, src/util/functions.js, src/util/tokenStore/redisTokenStory.js
Criado a logica para utilizar um prefix quando for utilizar o banco Redis.
Assim não pegando chaves de outro sistema que não lhe pertence.
Adicionado também quando colocar a palavra 'docker' o prefix e gerado pelo ip do server, assim mesmo se 
levantar vários container com a mesma imagem cada prefix será diferente permitindo um load balance.
=> Criado logica para utilizar um prefix no banco Redis

src/util/functions.js
fix: webhook url
Currently, if the url is not passed in the start-session, it also does not recognize the one in config.json
=> fix: webhook url

src/controller/messageController.js, src/routes/index.js
Adicionado a possibilidade de mandar uma lista de botões, pelo método sendButtonsList, buttons tem que ser array de objetos {"title": "Opção 1","rowId": "01"}
=> feat(release): Implementado método para mandar lista de botões

src/controller/deviceController.js
As mensagens privadas não devem ser tratadas no WPPConnect, elas são internas no ChatWoot e não devem ser encaminhadas.
=> Mensagens privadas do ChatWoot

src/util/chatWootClient.js
Quando a start session ocorre na primeira vez os eventos qrcode e status são gerados praticamente em simultâneo, com isso são gerados dois contatos dentro do chatwoot, adicionando atraso em um deles é possivel mitigar este comportamento, achei melhor adicionar o delay no qrcode pois ele é um evento que ocorre menos vezes do que o status.
=> Não gerar contato duplicado

src/util/chatWootClient.js
O filtro de status estava sendo feito apenas para conversas com status 'open', porém existem os status 'pending' e 'snoozed' que também devem ser consideradas como conversas ainda abertas... principalmente quando um robô é utilizado para o atendimento, nesse caso todas as conversas iniciam no com status 'pending', antes de fazer esse ajuste no código não estava conseguindo dar seguimento no fluxo do meu dialogflow porque a cada nova resposta ele gerava uma nova conversa...
=> Evita criar conversas adicionais erroneamente

src/util/chatWootClient.js
O source_id do contato não pode ser a message.id da primeira interação porque ela contem '@', e isso impede o uso do source_id em alguns endpoints do chatwoot impossibilitando por exemplo o UPDATE de mensagens. Alterei para que o source_id cadastrado seja o próprio numero de telefone pois ele será único entre os contatos nessa inbox do chatwoot.
=> Alterar source_id do contato

.dockerignore, Dockerfile, docker-compose.yml
as is hard to [server-cli](https://github.com/wppconnect-team/server-cli) keep up with wppconnect-server new features, this will allow to use wppconnect-server directly mounting the configuration file and volume for token, as suggested on docker-compose :)
=> Adds simple Dockerfile and docker-compose example

src/controller/messageController.js
replaced sendFileFromBase64 to sendFile with options
=> fix(message): fix depercated sendFileFromBase64

src/controller/messageController.js
This commit https://github.com/wppconnect-team/wppconnect-server/commit/3016f2f7ad65d18e762f51b98bdcb53bfd5ad8b5 from @icleitoncosta sadly breaked up sending options with image/file
so here is a quick fix.
because `options` is obj. not array to do `.length` with it.
so `options.length` is always `undefined` and now returns number / length
=> fix(message): fix sendFileFromBase64 with options

src/controller/catalogController.js
```
export async function setProductVisibility(req, res) {
const { id, value } = req.body;
if (!id || !value)
return res.status(401).send({
message: 'product id or value (false, true) was not informed',
});
try {
const result = await req.client.setProductVisibility(id, value);    <<<<<<<===============
res.status(201).json({ status: 'success', response: result });
} catch (error) {
res.status(500).json({ status: 'Error', message: 'Error on set product visibility.', error: error });
}
}
export async function updateCartEnabled(req, res) {
const { enabled } = req.body;
if (!enabled)
return res.status(401).send({
message: 'enabled (false, true) was not informed',
});
try {
const result = await req.client.setProductVisibility(enabled);    <<<<<<<===============
res.status(201).json({ status: …
```
=> fix: fixing set-cart-enable route

README.md
Disable the browser's sleep mode when idle, preventing the browser from going into sleep mode, this is useful for WhatsApp not to be in economy mode in the background, avoiding possible crashes
=> add new flag initialize session

.gitignore, src/util/chatWootClient.ts
Buscar somente as mensagens do contato e não todas as mensagens. Em alguns casos com um número alto de mensagens, buscar todas as mensagens, causa erro 500.
=> Otimização na função findConversation em chatWootClient.ts

src/util/createSessionUtil.ts
Issue: https://github.com/wppconnect-team/wppconnect-server/issues/1307
Basta passar no corpo da requisição /start-session, os valores de `deviceName` e `poweredBy` em `options`.
```
CURL POST /start-session
"options": {
"deviceName": "My Device",
"poweredBy": "My Powered"
}
```
=> Dynamic Device Name

src/config.ts, src/types/ServerOptions.ts, src/util/createSessionUtil.ts
Evento possibilitará webhook receber mensagens enviadas pelo dispositivo conectado (casos onde há envio da mensagem sem utilizar as rotas de send message), aprimorando a ausência da perda de mensagens pelo sistema do webhook.
Padrão está como false para não impactar em atualizações de projetos já existentes.
=> feat: Added onSelfMessage event for Webhook

README.md, src/util/functions.ts
Atualmente mesmo com o defaultBucketName setado, ele verifica se existe aquele bucket, o que não faz muito sentido, pois pela lógica se setei o bucket padrão, ele já deve (ou deveria) existir no S3.
A melhoria é muito simples, se já tiver o bucket padrão setado, não verifica se existe e posteriormente criando. Com essa mudança, tem duas principais melhorias:
1. Evitando requests desnecessários pra AWS S3 (quando verifica se existe o bucket, criando o bucket)
2. Isolando o user IAM da AWS pra ter acesso somente ao bucket padrão
Com essa melhoria, você só precisa criar um usuário com a seguinte política:
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "Stmt1688754007727",
"Action": [
"s3:ListBucket",
"s3:GetObject",
"s3:PutObject",
"s3:PutObjectAcl",
"s3:PutObjectTagging"
], …
```
=> Se existe bucket padrão setado não precisa verificar se existe

README.md, src/config.ts, src/types/ServerOptions.ts, src/util/createSessionUtil.ts, src/util/functions.ts
Atualmente apenas no webhook possui a possibilidade de fazer upload do conteúdo no S3, sendo assim, quando recebe um webhook nele já consta o fileUrl do upload feito no S3, todavia no websocket de 'received-message' ele recebe apenas os dados da mensagem, sem o fileUrl.
Com as novas mudanças o usuário poderá escolher onde quer fazer upload no S3, se quer que esse trabalho fique responsável quando envia o webhook ou pelo websocket, esse evento já será enviado com o fileUrl definido.
=> [Feature] - autoDownload and uploadS3 in Websocket

src/swagger.json
operationId was type incorrectly. Status session operationId was closeSession
=> Update operationId at /api/{session}/status-session in swagger.json

src/util/createSessionUtil.ts
This fix checks if message was received (encrypted) and not sent (causing error, because there is no media and it's not possible decrypt)
=> fix issue #1738

src/controller/sessionController.ts
The base64 qrcode returned after session creation was not detected by whatsapp app. This problem has been eliminated by adding qrOptions.
=> Not reading QRCode when starting a session

src/util/createSessionUtil.ts
Caso ocorra um timeout no Puppeteer, será gerada a seguinte exceção:
```python
error:    [teste:browser] Error no open browser
error:    [teste:browser] Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
error: 2024-07-30T16:54:11.637Z Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout! - TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
at ChromeLauncher.launch (/usr/src/wpp-server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:150:23)
at async PuppeteerExtra.launch (/usr/src/wpp-server/node_modules/puppeteer-extra/dist/index.cjs.js:128:25)
```
No meu caso, o problema ocorria porque algumas vezes a instância demorava um pouco mais para iniciar na …
=> Fechar sessão em caso de erro no Puppeter (Error no open bowser) (Initializing)

src/controller/sessionController.ts, src/routes/index.ts
feat: set online presence (Fixes iOS notification issue when wppconnect is connected)
Summary
This PR sets the user’s online presence using the setOnlinePresence endpoint. This resolves an issue where push notifications were not being received on iOS devices when WPPConnect was connected.
Context
When WPPConnect maintains an active session, iOS devices may not receive notifications due to the device being considered “online”. By explicitly setting the online presence, we ensure proper notification delivery behavior on iOS.
Changes
•	Call to setOnlinePresence added to enforce the correct presence state
•	Ensures that notification delivery works correctly when WPPConnect is active
Fixes
•	Push notifications not received on iOS while WPPConnect is connected
•	Fixes: …
=> feat: set online presence (Fixes notification does not receive on iOS when wppconnect is connected)

src/controller/deviceController.ts
When sending a private message from chatwoot, nothing should happen in the whatsapp chat, since it's just a internal message
When sending private messages, the last, non-private, message is sent to whatsapp insted, repeating the last message sent.
Return early when the message is private.
=> Bugfix: Repeating messages when sending private messages on chatwoot

src/controller/groupController.ts, src/routes/index.ts, src/swagger.json
Add a new endpoint to retrieve detailed group information.
- New route: `GET /api/:session/group-info/:groupId`
- Return group metadata: id, name, description, subject, creation date, last activity, and participants (with admin flag)
- Swagger docs updated
=> Add a new endpoint to retrieve detailed group information
