wppconnect-team/wppconnect-server

src/controller/deviceController.js
src/routes/index.js

Criado na api o metodo de metodos anteriores

Adicionado metodo chats anteriores

---

src/controller/deviceController.js
src/controller/groupController.js
src/routes/index.js

I've changed some routes to a single line to mantain a standard on the code. But i don't know how to deal with the Lint error :(

+ route group-revoke-link

---

src/util/tokenStore/factory.js

Fiz a atualização, e quando não informa ele da erro em todos os tokens, poderia deixar por padrão para ficar em arquivo se não informado ou se for null

Definir Padrão para Arquivo

---

src/controller/orderController.js
src/routes/index.js

Criado un controlador separado para a versao business
Criado dois metodos disponivel para a versao business

Adicionando Metodos para produtos - somente para versao business

---

src/controller/messageController.js
src/routes/index.js

Para funcionar o endpoint precisa que seja enviado pelo menos 2 botões para o parâmetro ```buttons```, assim ele envia os botões para o usuário selecionar qual deseja.
```
array: [
array: {
"buttonId": "id",
"buttonText: {
"displayText": "string"
},
"type": 1
}, array: {
"buttonId": "id",
"buttonText: {
"displayText": "string"
},
"type": 1
}
]
```

Adição de Endpoint SendButton

---

src/controller/messageController.js

Não é mais preciso passar a sessão, pois é enviada por padrão no retorno

Correção | Remove o envio de sessão

---

src/config.json
src/util/functions.js
src/util/tokenStore/redisTokenStory.js

Reverts wppconnect-team/wppconnect-server#213

Revert "Criado logica para utilizar um prefix no banco Redis"

---

src/config.json
src/util/functions.js
src/util/tokenStore/redisTokenStory.js

Reverts wppconnect-team/wppconnect-server#226

feat: ajustes redis

---

src/util/tokenStore/redisTokenStory.js

Copiado o metodo do file para o get do redis pois estava sobreescrevendo por falta dessa logica.

fix(release): Corrigido o webhook do redis que estava sobreescrevendo

---

src/config.json
src/util/createSessionUtil.js

Adicionado no arquivo config.json a capacidade de mudar o nome da sessão do aparelho de forma dinâmica

Mudança nome sessão do aparelho

---

src/controller/messageController.js
src/routes/index.js

Na rota de envio de imagem tinha um bug na validação, ele enviava a imagem, porém, retornava um erro justamente por tentar acessar uma propriedade que não existia.
A rota sendVoice enviava apenas base64, troquei o nome dela para sendVoice64 e criei uma rota sendVoice que envia o arquivo passando a url do arquivo no parâmetro path.

Ajustando pequenos bugs e criando rota

---

src/util/createSessionUtil.js

fix: login after disconnected from mobile

---

src/controller/deviceController.js

Fixing some functions

---

src/util/functions.js

fix: fixed error occurred when archiving chats, if there are no chats

---

src/util/tokenStore/mongodbTokenStory.js

fix: mongodbTokenStory update token

---

README.md
src/config.json
src/index.js
src/util/functions.js

feat: set maxListeners

---

src/controller/sessionController.js
src/util/functions.js

wppconnect-team/wppconnect#825

fix: treatment for decryptFile

---

src/util/createSessionUtil.js

Eventos que faltavam ser enviados via socket

feat: Socket emit on events

---

src/controller/messageController.js
src/routes/index.js
src/swagger.json

Corrigi a função de Send Buttons List pois estava sem funcionar
É necessária, pois irei utilizar ela no front em vue para enviar os botões

Bug fix on send list message

---

src/controller/catalogController.js
src/routes/index.js
src/swagger.json

Estou adicionando a funcionalidade de adicionar produto no catalogo do whatsapp business.

feat: add create product route

---

src/controller/groupController.ts

https://github.com/wppconnect-team/wppconnect-server/issues/1308

 Change-privacy-group and messages-admins-only duplicate function

---

src/controller/deviceController.ts

Fix Breaking Change from : https://github.com/wppconnect-team/wppconnect/pull/1875
```log
yarn run v1.22.19
$ npm run build:types && npm run build:js
> @wppconnect/server@2.2.5 build:types
> tsc
src/controller/deviceController.ts:989:35 - error TS2551: Property 'forwardMessages' does not exist on type 'Whatsapp & { urlcode: string; status: string; }'. Did you mean 'forwardMessage'?
989       response = await req.client.forwardMessages(
~~~~~~~~~~~~~~~
node_modules/@wppconnect-team/wppconnect/dist/api/layers/sender.layer.d.ts:299:5
299     forwardMessage(toChatId: string, msgId: string | string[], options?: ForwardMessagesOptions): Promise<boolean>;
~~~~~~~~~~~~~~
'forwardMessage' is declared here.
src/controller/deviceController.ts:995:35 - error TS2551: Property 'forwardMessages' does …
```

fix:forwardMessages

---

src/controller/messageController.ts

Esse PR tem como objetivo, fazer citação em outra mensagem através de áudio ptt e arquivos em base 64

Mensagem citada para áudio ptt em base64

---

Dockerfile

Feita alteração do Dockerfile para a instalação do sharp, que apresentou erro na ultima versão.

Instalação do Sharp via Dockerfile

---

src/index.ts
src/routes/index.ts

file:
- src/routes/index.ts
- src/index.ts

chore: add types to prevent editor errors

---

package.json

fix 'close-session' & 'status-session' open simultaneously

debug: auth card

---

docker-compose.yml

insert name in container

---

src/controller/deviceController.ts

Check if attachments is Push-to-talk and send this in chatwoot endpoint.

fix: Chatwoot Push-To-Talk
